# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b8cee8aaa707479fe8500757f3cd7cef069bb62e59e74f3b19ed33d6364c4737bc84dbdc5babe440a46a160c98232b2e49cd502b5b15563c68fa6789bdec18d

test:
  secret_key_base: fd61fd3b46dff3ae9e301c777d87a4c62d2e9f6f538d157d58259d69ebfa3f320000ae14d9c7cdf4ac5f7a32c171bc416cca1eabf6e11f3e988af5a5ade61e3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
